test_that("All files download and enhanced correctly.", {
  expect_no_error(load_enhanced_puf_file(2013))
  expect_no_error(load_enhanced_puf_file(2015))
  expect_no_error(load_enhanced_puf_file(2016))
  expect_no_error(load_enhanced_puf_file(2017))
  expect_no_error(load_enhanced_puf_file(2018))
  expect_no_error(load_enhanced_puf_file(2019))
  expect_no_error(load_enhanced_puf_file(2020))
  expect_no_error(load_enhanced_puf_file(2021))
  expect_no_error(load_enhanced_puf_file(2022))
  expect_no_error(load_enhanced_puf_file(2023))
  expect_no_error(load_enhanced_puf_file(2024))
})
